{
 "title": "njmon Dashboard",
 "tags": [
  "nmon",
  "nimon",
  "njmon"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "hostname",
    "query": {
     "query": "label_values(system_uptime{job=\"$job\"}, host)"
    }
   },
   {
    "name": "job",
    "query": {
     "query": "label_values(system_uptime, job)"
    }
   },
   { "name": "DS_NJMON", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Data collected by . . . . . . . . . . . . .",
   "type": "text",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "options": {
    "content": "<center><img src=\"http://nmon.sourceforge.net/docs/njmon-logo-foraixlinux200.png\"></img></center>\n\n\n\n"
   },
   "targets": [
    { "type": "prometheus" }
   ]
  },
  {
   "title": "CPU Busy",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "type": "prometheus",
     "expr": "100 - cpu_total_idle{host=\"$hostname\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Sys Load (1m)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "type": "prometheus",
     "expr": "system_load1{host=\"$hostname\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Sys Load (5m)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "type": "prometheus",
     "expr": "system_load5{host=\"$hostname\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Sys Load (15m)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "type": "prometheus",
     "expr": "system_load15{host=\"$hostname\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "RAM Used",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "type": "prometheus",
     "expr": "mem_used_percent{host=\"$hostname\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "SWAP Used",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "type": "prometheus",
     "expr": "swap_used_percent{host=\"$hostname\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Root FS Used",
   "type": "gauge",
   "description": "Root Filesystem",
   "gridPos": { "h": 4, "w": 2, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "type": "prometheus",
     "expr": "disk_used_percent{host=\"$hostname\",job=\"$job\",path=\"/\"}"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "type": "prometheus",
     "expr": "count(cpuinfo_cpu_cores{host=\"$hostname\",job=\"$job\"})"
    }
   ]
  },
  {
   "title": "RAM Total",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "type": "prometheus",
     "expr": "proc_meminfo_MemTotal{host=\"$hostname\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Zombie proc",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "type": "prometheus",
     "expr": "processes_zombies{host=\"$hostname\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Root FS Total",
   "type": "stat",
   "description": "Root Filesystem",
   "gridPos": { "h": 2, "w": 2, "x": 17, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "type": "prometheus",
     "expr": "disk_total{host=\"$hostname\",job=\"$job\",path=\"/\"}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 19, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "type": "prometheus",
     "expr": "system_uptime{host=\"$hostname\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "CPU Utilisation for Total System",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "type": "prometheus",
     "expr": "cpu_total_user{host=\"$hostname\",job=\"$job\"}",
     "legendFormat": "CPU User"
    },
    {
     "type": "prometheus",
     "expr": "cpu_total_iowait{host=\"$hostname\",job=\"$job\"}",
     "legendFormat": "CPU IOwait"
    },
    {
     "type": "prometheus",
     "expr": "cpu_total_sys{host=\"$hostname\",job=\"$job\"}",
     "legendFormat": "CPU System"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "type": "prometheus",
     "expr": "mem_used{host=\"$hostname\",job=\"$job\"}",
     "legendFormat": "mem_used"
    },
    {
     "type": "prometheus",
     "expr": "mem_shared{host=\"$hostname\",job=\"$job\"}",
     "legendFormat": "mem_shared"
    },
    {
     "type": "prometheus",
     "expr": "mem_buffered{host=\"$hostname\",job=\"$job\"}",
     "legendFormat": "mem_buffered"
    },
    {
     "type": "prometheus",
     "expr": "mem_cached{host=\"$hostname\",job=\"$job\"}",
     "legendFormat": "mem_cached"
    }
   ]
  },
  {
   "title": "FileSystems Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "type": "prometheus",
     "expr": "disk_used{host=\"$hostname\",job=\"$job\"}",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Disks R/W KB",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "KiBs" } },
   "yaxes": [
    { "format": "KiBs", "label": " read (-) / write (+)" }
   ],
   "targets": [
    {
     "type": "prometheus",
     "expr": "disks_wkb{host=\"$hostname\",job=\"$job\"}",
     "legendFormat": "/dev/{{disk_name}} - Write KB"
    },
    {
     "type": "prometheus",
     "expr": "disks_rkb{host=\"$hostname\",job=\"$job\"}",
     "legendFormat": "/dev/{{disk_name}} - Read KB"
    }
   ]
  },
  {
   "title": "Network Bytes/sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "type": "prometheus",
     "expr": "networks_ibytes{host=\"$hostname\",job=\"$job\",network_name!=\"lo\"}",
     "legendFormat": "{{network_name}} - inbound"
    },
    {
     "type": "prometheus",
     "expr": "networks_obytes{host=\"$hostname\",job=\"$job\",network_name!=\"lo\"}",
     "legendFormat": "{{network_name}} - outbound"
    }
   ]
  },
  {
   "title": "Top Status",
   "type": "table",
   "gridPos": { "h": 8, "w": 7, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "type": "prometheus",
     "expr": "processes_cpu_percent{host=\"$hostname\",job=\"$job\"}",
     "legendFormat": "{{process_name}}"
    }
   ]
  }
 ]
}